version: '3'

services:

  webserver:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.141
    ports:
      - "8081:80"

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: simple_invoices
      MYSQL_ROOT_PASSWORD: simple_invoices
    restart: always
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume: